### ISSUE TITLE
Make it possible to copy the RAW text when viewing pods/rc etc kubernetes json

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-console#118]
You cannot copy/paste all this text its disabled. See screenshot

![screen shot 2016-03-10 at 10 11 19 am](https://cloud.githubusercontent.com/assets/477100/13664610/9787298c-e6a8-11e5-8cca-f43822b1c11c.png)

**Comment by davsclaus** [comment]
Also @gashcrumb when you click the "raw" button to see it, then the text area do not show all the text at first, you have to click or scroll a bit down to make it show it all.

Maybe there is a better canvas or something you can use to host the text. And would be awesome to make copy/paste work.

**Comment by gashcrumb** [comment]
That is so weird that it'd be totally disabled like that, will look into it...

**Comment by gashcrumb** [comment]
At least on replication controllers you can click 'Edit' and then copy works.  Must be a weird quirk with CodeMirror in read only mode, will see if I can get it working normally.  I didn't see the issue with text not showing at least against a current build, I did go through and switch over a bunch of editors to use hawtio-editor instead of ui-codemirror, the latter always seems to have that problem.
