### ISSUE TITLE
Your session has expired in title bar

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-console#2]
Hi

I had the fabric8-console in a brower tab, and then went away for lunch for about 1 hour or so.
And when I got back I noticed the browser title says "Your session has expired" but I am able to continue browse the pages. And the title stills says about the expire.

I wonder if the web console should not auto logout or something instead?

![session-expired](https://cloud.githubusercontent.com/assets/477100/7725697/5aaddabc-fefd-11e4-94fa-cc11912cf660.png)

**Comment by jimmidyson** [comment]
Log out will be based on token expiry as we're logging in to OpenShift oauth remember. But we should handle expiry & also refresh tokens, although this is probably one for hawtio-oauth module?

**Comment by davsclaus** [comment]
Yeah I say this again today with latest code.

**Comment by gashcrumb** [comment]
Found where it's coming from.  It's actually from the keycloak plugin in hawtio-oauth, apparently ng-idle was added for that which is fine, just need to update it so that it's turned on only when keycloak is configured.

AFAIK openshift doesn't yet support token refreshes and just hands out long-lived tokens.

**Comment by gashcrumb** [comment]
K, a bower update locally will sort this now...
