### ISSUE TITLE
Console on openshift - An authentication error occurred.

### ISSUE THREAD

**Issue by xelfe** [fabric8io/fabric8-console#263]
I'm using openshift origin 3.5 with authentification on github.

When I'm trying to access the web console of fabric8 I got the message; An authentication error occurred.

Into the url we can see the callback of github; http://openshift:8443/oauth2callback/github....

**Comment by xelfe** [comment]
After trying some method for the install, I've found that everything work with gofabric8 deploy.

**Comment by Rammmsankar** [comment]
hi Xelfe , which method ? I am also facing same issue

**Comment by haejunj** [comment]
oc delete user demo  and oc delete identity github:demo

**Comment by Rammmsankar** [comment]
sorry for late reply ... it is displaying 
"Error from server (NotFound): identities.user.openshift.io "github:demo" not found" I am using 
 oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://internal-openshift-master.xxx.xx:443
openshift v3.6.0+c4dd4cf

Also please help for configuring the public url . now it's opening on port 443 and redirecting to github 

thanks in advance for the help

**Comment by haejunj** [comment]
oc delete user <your_account>
oc get user
oc delete identity <deleted account info>

**Comment by Rammmsankar** [comment]
thanks for fast reply 
oc get user / identity showing no resources found i deleted the user demo

**Comment by Rammmsankar** [comment]
oc login
Login failed (401 Unauthorized)
You must obtain an API token by visiting https://openshift-master.xxx.xx/oauth/token/request

**Comment by Rammmsankar** [comment]
now another issue coming as oc cluster up it shows 
# oc cluster up
Starting OpenShift using openshift/origin:v3.6.0 ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v3.6.0 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... FAIL
   Error: a port needed by OpenShift is not available
   Caused By:
     Error: ports in use: [443 10250 53 8053]
Please help
